### ISSUE TITLE
How can I  run this Project ?? 

### ISSUE THREAD

**Issue by guojingzoe** [ifcquery/Express2SourceConverter#1]
Sorry to trouble you ,I'm working on a project,in this project, Ifc files need to be translated into entity classes and stored on Hbase. I wanted to parse the entity class in Java,but I found that is so difficult for me .I am so exciting  to find your project.When I download it,I also refer to the Internet, download the WinGW, and CLion ,after importing this project , it unable to run. could you tell me how can I run this project ?

It is also the first time to speak on github. If there is a grammar mistake, ask your forgiveness,I am looking forward to your reply.

**Comment by guojingzoe** [comment]
@ifcquery

**Comment by ifcquery** [comment]
Please report issues in case when an error in the source code of the project occured.
If you just need help with your development environment, professional support is available.
In that case, you can contact me on www.ifcquery.com

**Comment by guojingzoe** [comment]
![my](https://user-images.githubusercontent.com/28012963/34667231-2145c21e-f4a3-11e7-8427-33979cf83991.png)
Thank you very much for your reply!
I open this project with clion, and all the support associated with qt is red.
